[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "minimalCore"
authors = [{name = "yuchen", email = "yuchen414@gmail"}]
dynamic = ["version", "description"]
